## EdgeX Foundry Developer docker compose file
## Login to the nexus3.edgexfoundry.org:10003 registry instance with:
## docker login nexus3.edgexfoundry.org:10003
## u: docker, p: docker

version: '2'
services:
  volume:
    image: edgexfoundry/docker-edgex-volume
    container_name: edgex-files
    networks:
      - edgex-network
    volumes:
      - /data/db
      - /edgex/logs
      - /consul/config
      - /consul/data

  config-seed:
    image: nexus3.edgexfoundry.org:10003/docker-core-config-seed
    ports:
        - "8400:8400"
        - "8500:8500"
        - "8600:8600"
    container_name: edgex-config-seed
    hostname: edgex-core-config-seed 
    networks:
      edgex-network:
        aliases:
            - edgex-core-consul
    volumes_from:
      - volume
    depends_on:
      - volume

  mongo:
    image: edgexfoundry/docker-edgex-mongo
    ports:
      - "27017:27017"
    container_name: edgex-mongo
    hostname: edgex-mongo
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume

  logging:
    image: nexus3.edgexfoundry.org:10003/docker-support-logging
    ports:
      - "48061:48061"
    container_name: edgex-support-logging
    hostname: edgex-support-logging
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo

  notifications:
    image: nexus3.edgexfoundry.org:10003/docker-support-notifications
    ports:
      - "48060:48060"
    container_name: edgex-support-notifications
    hostname: edgex-support-notifications
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging

  metadata:
    image: nexus3.edgexfoundry.org:10003/docker-core-metadata
    ports:
      - "48081:48081"
    container_name: edgex-core-metadata
    hostname: edgex-core-metadata
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging

  data:
    image: nexus3.edgexfoundry.org:10003/docker-core-data
    ports:
      - "48080:48080"
      - "5563:5563"
    container_name: edgex-core-data
    hostname: edgex-core-data
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - notifications

  command:
    image: nexus3.edgexfoundry.org:10003/docker-core-command
    ports:
      - "48082:48082"
    container_name: edgex-core-command
    hostname: edgex-core-command
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - metadata

  scheduler:
    image: nexus3.edgexfoundry.org:10003/docker-support-scheduler
    ports:
      - "48085:48085"
    container_name: edgex-support-scheduler
    hostname: edgex-support-scheduler
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - metadata
      - command

  export-client:
    image: nexus3.edgexfoundry.org:10003/docker-export-client
    ports:
      - "48071:48071"
    container_name: edgex-export-client
    hostname: edgex-export-client
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - notifications
      - metadata
      - data

  export-distro:
    image: nexus3.edgexfoundry.org:10003/docker-export-distro
    ports:
      - "48070:48070"
      - "5566"
    container_name: edgex-export-distro
    hostname: edgex-export-distro
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - notifications
      - metadata
      - data
      - export-client

  rulesengine:
    image: nexus3.edgexfoundry.org:10003/docker-support-rulesengine
    ports:
      - "48075:48075"
    container_name: edgex-support-rulesengine
    hostname: edgex-support-rulesengine
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - metadata
      - command
      - export-distro

#################################################################
# Device Services
#################################################################

  device-virtual:
    image: nexus3.edgexfoundry.org:10003/docker-device-virtual
    ports:
      - "49990:49990"
    container_name: edgex-device-virtual
    hostname: edgex-device-virtual
    networks:
      - edgex-network
    volumes_from:
      - volume
    depends_on:
      - volume
      - config-seed
      - mongo
      - logging
      - metadata
      - data
      - command
      
  # device-bacnet:
    # image: nexus3.edgexfoundry.org:10003/docker-device-bacnet
    # ports:
      # - "49986:49986"
    # container_name: edgex-device-bacnet
    # hostname: edgex-device-bacnet
    # networks:
      # - edgex-network
    # volumes_from:
      # - volume
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-bluetooth:
    # image: nexus3.edgexfoundry.org:10003/docker-device-bluetooth
    # ports:
      # - "49988:49988"
    # container_name: edgex-device-bluetooth
    # hostname: edgex-device-bluetooth
    # networks:
      # - edgex-network
    # volumes_from:
      # - volume
    # privileged: true
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-fischertechnik:
    # image: nexus3.edgexfoundry.org:10003/docker-device-fischertechnik
    # ports:
      # - "49985:49985"
    # container_name: edgex-device-fischertechnik
    # hostname: edgex-device-fischertechnik
    # networks:
      # - edgex-network
    # volumes_from:
      # - volume
    # privileged: true
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-modbus:
    # image: nexus3.edgexfoundry.org:10003/docker-device-modbus
    # ports:
      # - "49991:49991"
    # container_name: edgex-device-modbus
    # hostname: edgex-device-modbus
    # networks:
      # - edgex-network
    # volumes_from:
      # - volume
    # privileged: true
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-mqtt:
    # image: nexus3.edgexfoundry.org:10003/docker-device-mqtt
    # ports:
      # - "49982:49982"
    # container_name: edgex-device-mqtt
    # hostname: edgex-device-mqtt
    # networks:
      # - edgex-network
    # volumes_from:
      # - volume
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command
      
  # device-snmp:
    # image: nexus3.edgexfoundry.org:10003/docker-device-snmp
    # ports:
      # - "49989:49989"
    # container_name: edgex-device-snmp
    # hostname: edgex-device-snmp
    # networks:
      # - edgex-network
    # volumes_from:
      # - volume
    # depends_on:
      # - volume
      # - config-seed
      # - mongo
      # - logging
      # - metadata
      # - data
      # - command

networks:
  edgex-network:
    driver: "bridge"
...
